### ISSUE TITLE
Error performing any operation

### ISSUE THREAD

**Issue by Kudlaty01** [shanehofstetter/youtrack-cli#1]
No matter what operation (project ls or user info) I try I always get the following message:

> Cannot set property '0' of undefined

When using interactive mode and choosing a task I get
>(node:4329) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'find' of undefined
    at transformer (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/dist/commands/workitem/createWorkItemCommand.js:31:59)
    at InputPrompt.render (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/inquirer/lib/prompts/input.js:58:18)
    at InputPrompt.onError (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/inquirer/lib/prompts/input.js:93:10)
    at SafeSubscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Observable.js:66:21)
    at SafeSubscriber.__tryOrUnsub (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:209:16)
    at SafeSubscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:147:22)
    at Subscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:90:26)
    at Subscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at TakeUntilSubscriber.Subscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:90:26)
    at TakeUntilSubscriber.Subscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at FilterSubscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/operators/filter.js:52:30)
    at FilterSubscriber.Subscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at RefCountSubscriber.Subscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:90:26)
    at RefCountSubscriber.Subscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at Subject.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subject.js:60:25)
    at ConnectableSubscriber.Subscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:90:26)
    at ConnectableSubscriber.Subscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
    at InnerSubscriber._next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/Subscriber.js:67:18)
    at /home/kudlaty01/.nvm/versions/node/v10.13.0/lib/node_modules/youtrack-cli/node_modules/rxjs/internal/util/subscribeToPromise.js:7:24
(node:4329) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:4329) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have passed throught setup and configured the tool with my YT account.
What might be the problem?
I am using Node v10.13.0

**Comment by shanehofstetter** [comment]
Hi, 
the specific error that you're getting is caused by the fact that the returned issue object from youtrack has undefined fields (this should normally be an array), which is kind of strange. what youtrack version are you using?

**Comment by Kudlaty01** [comment]
YouTrack 2018.3
The interactive mode referred to ```youtrack w c```
For ```youtrack user show``` I get
> error: missing required argument `login'

and for ```youtrack workitem ls <issueId>```:
> workItems.sort is not a function

For ```youtrack show <itemId>``` and ```youtrack comment ls``` I get nothing
```youtrack user info```:
> Cannot set propeprty '0' of undefined

**Comment by shanehofstetter** [comment]
Was the setup command successful? Could you run it again?

As for the command `youtrack user show`, this one needs a username as argument, e.g. `youtrack user show <your-login-name>`. Could you try the command `youtrack workitem ls <issueId> --raw` and post the output, and the same for `youtrack user info --raw`)?

**Comment by shanehofstetter** [comment]
Glad to hear it works now, thanks for the PR.
